# Generated by Django 4.2.1 on 2023-06-03 22:40

from django.conf import settings
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('type', models.CharField(choices=[('dm', 'DM'), ('group', 'Group')], default='dm', max_length=10)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, unique=True)),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
