# Generated by Django 4.2.1 on 2023-06-03 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_module', '0002_alter_chatroom_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='member',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
