# Generated by Django 4.2.1 on 2023-06-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0003_remove_chatroom_member_chatroom_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='slug',
        ),
    ]
