# Generated by Django 4.2.1 on 2023-06-04 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_module', '0004_remove_chatroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='member',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
