# Generated by Django 4.2.1 on 2023-06-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0006_chatroom_slug_alter_chatroom_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='slug',
        ),
    ]
