# Generated by Django 4.2.1 on 2023-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars', verbose_name='avatar'),
        ),
    ]
