# Generated by Django 4.2.1 on 2023-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_module', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=50, null=True, verbose_name='status'),
        ),
    ]
